AOSP support
Squashed commit of the following:

commit d579ef86e19310f921804ef07585c1b1876f5731
Author: Simon1511 <me@simon1511.de>
Date:   Sat Aug 26 16:52:11 2023 +0200

    sm7325: techpack: display: enable HBM alongside dimming

    Change-Id: I66adadd139a4fe716d66db3669ea61b43b9dbad3

commit 7992cfebf324f424839c475b77b12e2e6ec3f18b
Author: Simon1511 <me@simon1511.de>
Date:   Tue Aug 15 15:30:46 2023 +0200

    sm7325: techpack: display: samsung: prevent accidental HBM triggers

    Change-Id: I447efc78e48691dd99735996981e10c70ce409c5
    Signed-off-by: Simon1511 <me@simon1511.de>

commit 89484033f58a840c7b5bfbe110981c9dc037b020
Author: Simon1511 <me@simon1511.de>
Date:   Tue Aug 15 15:33:58 2023 +0200

    Revert "sm7325: techpack: msm: samsung: properly enable/disable HBM"

    This reverts commit 0076142799301494a243986f25d097d2297df1b2.

    Change-Id: Ifed59e7483b5e92f3285d9c63d17040a376f4e8b

commit 869ced5697fcb497ba0b623f5763adbde22fc30b
Author: Simon1511 <me@simon1511.de>
Date:   Sun Aug 6 14:54:52 2023 +0200

    sm7325: battery: common: remove sec_vote calls

    * They aren't neccessary for starting/stopping charging using batt_slate_mode and break the flashlight when slate mode is enabled

    Change-Id: I0c1fe742b3c3b0d006d5d7c840e6622cfede35c1

commit d601dcdc148c6287195d564ca5e38290907a1bd9
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Sun Dec 18 21:40:00 2022 +0200

    sm7325: techpack: display: ignore CSC config on FOD layer

    FOD performance decreases if the color of the icon is not
    exactly white, which happens when night light is enabled.
    Skip CSC for the FOD layer.

    Change-Id: Icb202690ec58e807b612fffe479c8e7c5c3b5d03

commit bb1a5d507e75ac01a999b03a73730be0aed03dbd
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Mon Oct 31 12:23:22 2022 +0200

    sm7325: techpack: display: translate PCC to CSC

    PCC cannot be applied per-plane, but CSC can. Translate PCC to CSC
    to allow skipping it for some planes.

    Change-Id: I76fa04fed6bcc9426cf2a38c58c23e49e27b8750

commit ed6372ae28d5aac9a90d7070ebc135a4f9fb3336
Author: Simon1511 <me@simon1511.de>
Date:   Wed Nov 9 20:17:11 2022 +0100

    sm7325: input: sec_input: stm: limit physical proximity sense range

    * On stock ROM proximity only changes if changes occur near to the sensor. However on AOSP proximity already changes if a finger is placed somewhere between the upper half and the middle of the screen, making it impossible to for example pull down the notification panel during a phone call because the screen constantly turnes off. Samsung seems to apply something remotely similar on their stock ROM by creating a whole new virtual sensor.
    * We now check if the area around the sensor (1400-2800 on the X axis, 0-700 on the Y axis) is touched and only then report proximity changes.
    * To not break proximity reporting during screen off we also check if the panel is in LPM state

    Change-Id: I22cb2f15cbb8a852b416642b47e1eb2799053d7e

commit c1aa7a36b9a207341f89395f29c1762b5f0c0a5d
Author: Simon1511 <me@simon1511.de>
Date:   Sat May 6 14:00:06 2023 +0200

    sm7325: techpack: msm: samsung: properly enable/disable HBM

    * In some rare cases the backlight brightness would be reset to what HBM brightness was, locking our brightness at a high level

    Signed-off-by: Simon1511 <me@simon1511.de>
    Change-Id: I578cfe4e052e621fc0fc21bdfd2a651c6aa4d269

commit e9ac5bf190af1c2d07b0913b0ea959c7ae18b538
Author: Roman Birg <roman@cyngn.com>
Date:   Wed Jul 20 17:47:14 2022 +0200

    sm7325: input: misc: hall_ic: Report SW_LID instead of SW_FLIP

    * Android expects SW_LID for lid events.

    Change-Id: Iebffbabdbb3748eec4f887ebd227c67adf01d8ef | AOSP
    Signed-off-by: Roman Birg <roman@cyngn.com>

commit c64e7888abe971e109e7827c0a6b047f4f16a33b
Author: Simon1511 <me@simon1511.de>
Date:   Mon Oct 17 12:21:58 2022 +0200

    sm7325: input: sec_input: Only report KEY_BLACK_UI_GESTURE for singletap

    Change-Id: I89b0f5b35b998924a8f2e31ecc9800b3e4fd2d28

commit f73567a634fe6e50a73407ddfcd96d33ec8e0d30
Author: Simon1511 <simon2002.schoenmackers@gmail.com>
Date:   Fri Jul 1 15:18:58 2022 +0200

    sm7325: input: sec_input: Add sysfs to track FOD pressed state

    /sys/class/sec/tsp/input/fod_pressed
    0 -> not pressed
    1 -> pressed

    Change-Id: Ifb2f432b1286bfc2a76a7c462326562569942ae5

commit c9d3ba93401cfca1a811e829c02dc1ea8fa5c452
Author: Demon000 <demonsingur@gmail.com>
Date:   Sat Jul 2 20:43:01 2022 +0200

    techpack: display: msm: implement fod handling

    Change-Id: Id300229200c9895f309f1a44c9980642da084a89

commit 4472f7c83cc71421a3416372ca9b1e3fe05011e0
Author: Simon1511 <simon2002.schoenmackers@gmail.com>
Date:   Sun Jul 3 14:28:26 2022 +0200

    sm7325: techpack: display: make Samsung HBM work

    On stock ROM Samsung writes the brightness value for the finger mask to /sys/class/lcd/panel/mask_brightness and then turns on the mask layer. However we don't know how they actually turn it on. Therefore enable/disable the finger mask every time we write something to mask_brightness.

    Signed-off-by: Simon1511 <simon2002.schoenmackers@gmail.com>
    Change-Id: If14119b8856d329f6049701fd16d20c39301f712

commit 1099af2715606ae7a2da64ee42c20a590bbac783
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 16:00:30 2022 +0200

    techpack: display: sde_crtc: setup dim layer

    Change-Id: I267c6692374f368e6adb31bf28692330130cd720

commit e3cf47f368011aadcb5f433f81ddd710a5655fa5
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 15:59:25 2022 +0200

    techpack: display: sde_plane: expose method to check if plane is FOD

    Change-Id: Iee3baea1e89cd4573021ce500fb1ed653add410f

commit 2806597809da94621ed0a95f0e150aeefc225326
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 15:15:59 2022 +0200

    techpack: display: dsi_panel: expose FOD dim and method to set FOD HBM

    Change-Id: I439f536efefb7b338462ccf6d03b078cea76c1c3

commit 2b89bbdb478f9a107fc39f477ab096cd83124b39
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Fri Sep 10 00:47:53 2021 +0300

    techpack: display: dsi_panel: track real backlight value

    Change-Id: I5b6d71687cc6c208381c285187eaa1a6bfffecc7

commit a69a3f41e78bbde91f835e57d810722e24da8fbd
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 15:08:04 2022 +0200

    techpack: display: dsi_panel: read FOD dimming LUT

    Change-Id: I23f7914ce0adf6c1942c09212516ed5f6b22d289

commit cf14611d06564e92148d180a9a3bda9a2b2d4206
Author: GuaiYiHu <guaiyihu@foxmail.com>
Date:   Fri Oct 8 12:09:37 2021 +0200

    techpack: display: sde_hw_mdss: Increase sde stage to map zpos changes

    Otherwise fingerprint payment won't work in some apps.

    Change-Id: I94f6a32751db8a5771362923d376efcde9845f9f

commit f2c8d718fb3103ad233b0ba0a2487a217574a09b
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 10:35:42 2022 +0200

    teckpack: display: dsi_panel: create empty ettributes group

    Change-Id: Ia1e747272240d380c82843d9faeeedac7bc58d9b

commit 96ba74fd8bd6d562cf87dd2c2fccc8c8c3c3fa7c
Author: DevriesL <therkduan@gmail.com>
Date:   Mon Dec 31 21:42:21 2018 +0800

    techpack: display: dsi_display: expose method to get main display

    Change-Id: Id670875adc18659521c424a716cf0ef194f9627f

commit e0de19110ec5d19b9c582266912aa05ef2a1a24b
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 17:01:10 2022 +0200

    techpack: display: sde_plane: extract bit in ZPOS into FOD

    Change-Id: If4dc829375682817ce4b778749710d9bda33491a

commit 7caf57845cbe4ce7943e6ad0cfd7400cc1c15a50
Author: Cosmin Tanislav <demonsingur@gmail.com>
Date:   Thu Feb 10 17:00:39 2022 +0200

    techpack: display: sde_plane: add FOD prop

    Change-Id: I4799a64e90cfd3e1fd464f90ce13a5db75f81dd3

commit df42ba9aa6624c87e13c800cef1230aeb0b6654f
Author: Simon1511 <simon2002.schoenmackers@gmail.com>
Date:   Thu Mar 24 17:46:21 2022 +0100

    sm7325: techpack: display: Remove restrictions for sensorRGB

    Signed-off-by: Simon1511 <simon2002.schoenmackers@gmail.com>
    Change-Id: I9266d6a82859a4132c011301085861b289ff1553

commit 2283bff1b0f5b467cf70124a330326acd0c1c19e
Author: Zhao Wei Liew <zhaoweiliew@gmail.com>
Date:   Thu Dec 15 21:23:30 2016 +0100

    techpack: display: samsung: mdnie: Expose no. of display modes

    CMHW uses this to determine the display modes supported by the device.

    Change-Id: I32bdd71f1f336967d41ec4b36f8620ce36cace4b

commit 41006f605b55e72ad7df8abca9a97791c375adc6
Author: apass3rby <100168186+apass3rby@users.noreply.github.com>
Date:   Fri Jul 1 14:32:26 2022 +0200

    sm7325: input: sec_input: correct low power proximity reporting

    Change-Id: I2d261ca14906e96312fe0b23cb79585341c30931

commit f69fabfdc40385faf27d39054671eaf2b6111ca8
Author: apass3rby <100168186+apass3rby@users.noreply.github.com>
Date:   Mon May 9 10:40:13 2022 +0200

    sm7325: input: sec_input: Invert reported proximity values

    * On stock higher value indicates closer proximity while on AOSP it is expected to be the other way around

    Change-Id: Ib27d408f5e45dbd42b61bc37f0f3ef30e28157b9

Signed-off-by: BlackMesa123 <giangrecosalvo9@gmail.com>

sm7325: input: sec_input: synaptics: Add sysfs to track FOD pressed state

/sys/class/sec/tsp/input/fod_pressed
0 -> not pressed
1 -> pressed

Change-Id: Ifb2f432b1286bfc2a76a7c462326562569942ae5

sm7325: dts: get rid of in-kernel vendor mounting

ERROR: recovery: [libfs_mgr] Error updating for slotselect

Change-Id: I03ceac62b333f6440dc4b7653b1633e9add27fd4

sm7325: input: sec_input: stm: force enable hover proximity sensor

The sensors HAL passes "1" to /sys/class/sec/tsp/ear_detect_enable, which leads to the proximity sensor being enabled.

So far it seems like 1 enables touch proximity, whereas 3 enables both hover proximity and touch proximity. It is yet to figure out if and what 2 does, but for now force enable the hover feature by altering the value passed by the HAL to 3.

Only enable hovering when the screen is not in LPM because turning on the hover feature breaks proximity when in LPM. While in LPM touch proximity will be used, otherwise touch proximity will be disabled.

Additionally we need to reset fod_pressed to 0 once we're entering LPM because enabling hovering sometimes prevents the driver from running into FTS_SPONGE_EVENT_GESTURE_ID_FOD_RELEASE, leaving fod_pressed sysfs at 1.

Change-Id: I7d77a79772d4661c5d1dc7dc64e144299c8f26d5
Signed-off-by: Simon1511 <me@simon1511.de>

techpack: msm: sde: Fallback to PCC for color invert

 * After the conversion from PCC to CSC for color trasformation,
   all filters work correctly and are converted properly to CSC,
   except for the color invert filter
 * This filter is the only one using the `c` constant coefficient
   in PCC, and it's almost impossible to conver to CSC, because
   the PCC reported values are far off from the regular scale of
   values that is being used, which makes converting the filter
   to CSC extra complex
 * To work around this, force PCC for all color filters when color
   invert is enabled, which has the downside of not behaving as well
   as CSC when using FOD, but still works just as good for all
   other contexts
 * We can use the `c` coefficient to understand if color invert is
   enabled, since this is the only color filter that sets the value
   to anything other than 0 (`32640`).

Simon1511: check for blob being NULL

Change-Id: I097413be9c519c22ee71483bdc084512f05e0465

sm7325: techpack: msm: samsung: reset finger mask state on screen off

Change-Id: I70aade584e97b8031434eceb73c8e90770b1e7f5